#!/bin/bash

# Script for changing Numix base folder style

# Copyright (C) 2014
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (version 3+) as
# published by the Free Software Foundation. You should have received
# a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.

# Allows timeout when launched vai 'Run in Terminal'
function sucess() { sleep 3; exit 0; }
function gerror() { sleep 5; exit 1; }

if [ -z "$1" ]; then
    :
else
    case "$1" in
        -c|--colours)
            echo -e \
                "This is a list of currently supported folder\n" \
                "\rcolours that can be used to replace the default.\n\n" \
                "\rdefault - reverts any previous colour change\n" \
                "\rblue    - 42a5f5\n" \
                "\rbrown   - 8d6e63\n" \
                "\rgreen   - 66bb6a\n" \
                "\rgrey    - bdbdbd\n" \
                "\rorange  - f57c00\n" \
                "\rpink    - f06292\n" \
                "\rpurple  - 7e57c2\n" \
                "\rred     - ef5350\n" \
                "\ryellow  - ffca28\n" \
                "\rcustom  - choose your own colours"
            sucess ;;
        -s|--styles)
            echo -e \
                "This is a list of currently supported folder\n" \
                "\rstyles that can be used to replace the default.\n\n" \
                "\r0 - default folder theme (uninstall)\n" \
                "\r1 - the original folder design\n" \
                "\r2 - plain design which matches our Legacy themes\n" \
                "\r3 - tilted design which never made it to production\n" \
                "\r4 - one that launched with the redesign of Circle\n" \
                "\r5 - curvy design which never made it to production\n" \
                "\r6 - the current new design that landed in 2015"
            sucess ;;
        -h|--help)
            echo -e \
                "A script for changing the Numix base folder\n" \
                "\rstyle and colour.\n\n" \
                "\rRunning as root makes the change globally,\n" \
                "\rotherwise it is only made locally. Run as\n" \
                "\rappropriate to your Numix installation.\n\n" \
                "\rUsage: numix-folders [OPTION]\n" \
                "\r  -c, --colours \t List of available colours.\n" \
                "\r  -s, --styles \t\t List of available styles.\n" \
                "\r  -h, --help \t\t Displays this help menu."
            sucess ;;
        *)
            echo -e \
                "numix-folders: invalid option -- '$1'\n" \
                "\rTry 'numix-folders --help' for more information."
            gerror ;;
    esac
fi

cuser="${SUDO_USER:-$USER}"
if [ -d /home/"$cuser"/.local/share/icons/Numix/ ]; then
    dir=/home/"$cuser"/.local/share/icons
elif [ -d /home/"$cuser"/.icons/Numix ]; then
    dir=/home/"$cuser"/.icons
elif [ -d /usr/share/icons/Numix/ ]; then
    if [[ $UID -ne 0 ]]; then
        echo -e \
            "You appear to have Numix instaled globally.\n" \
            "\rPlease run this script again as root"
        gerror
    else
        dir=/usr/share/icons
    fi
else
    echo -e \
        "You don't appear to have Numix installed! Please\n" \
        "\rinstall it and run this script again."
    gerror
fi

read -p "Which folder style do you want? " answer
if [ -z "$answer" ]; then
    style="0"
elif [ -d styles/"$answer" ]; then
    style="$answer"
else
    echo -e \
        "Oops! You've chosen an invalid style number.\n" \
        "\rRun 'numix-folders --styles' for an option list"
    gerror
fi

read -p "Which folder colour do you want? " answer
if [ -z "$answer" ]; then
    colour="default"
elif [ "$answer" == "custom" ]; then
    colour="custom"
    read -p "Choose first colour (main colour) in hex notation (e.g. 000000): " colour1
    read -p "Choose second colour (background colour) in hex notation (e.g. 000000): " colour2
    read -p "Choose third colour (dark background colour) in hex notation (e.g. 000000): " colour3
    if ! [[ $colour1 =~ ^[0-9A-Fa-f]{6}$ ]] || \
       ! [[ $colour2 =~ ^[0-9A-Fa-f]{6}$ ]] || \
       ! [[ $colour3 =~ ^[0-9A-Fa-f]{6}$ ]]; then
       echo -e \
           "Oops! One or more of your chosen custom colours were invalid.\n" \
           "\rBe sure to use valid hex values with six digits (e.g. 000000)"
       gerror
    fi
elif [ -d colours/"$answer" ]; then
    colour="$answer"
else
    echo -e \
        "Oops! You've chosen an invalid colour.\n" \
        "\rRun 'numix-folders --colours' for an option list"
    gerror
fi

cp -rf styles/"${style}"/Numix/* "${dir}"/Numix/

if [ "$colour" == "custom" ]; then
    find ${dir}/Numix/*/{actions,places}/*custom* \
        -exec sed -i --follow-symlinks "s/replacecolour1/#$colour1/g" {} \; \
        -exec sed -i --follow-symlinks "s/replacecolour2/#$colour1/g" {} \; \
        -exec sed -i --follow-symlinks "s/replacecolour3/#$colour3/g" {} \;
fi

currentcolour=$(readlink ${dir}/Numix/16x16/places/folder.svg | cut -d '-' -f 1)
links=$(find -L ${dir}/Numix/*/{actions,places} -xtype l)

for link in $links; do
    newlink=$(readlink "${link}");
    if [[ $newlink == *"$currentcolour"* ]]; then
        newlink=${newlink/${currentcolour}/${colour}}
        ln -sf "${newlink}" "${link}"
    fi
done

chown -R "$cuser" "${dir}"/Numix/
gtk-update-icon-cache -f "${dir}"/Numix/
if [ -d "${dir}"/Numix-Circle/ ]; then
    cp -rH styles/"${style}"/Numix-Circle/* "${dir}"/Numix-Circle/
    chown -R "$cuser" "${dir}"/Numix-Circle/
    gtk-update-icon-cache -f "${dir}"/Numix-Circle/
fi
if [ -d "${dir}"/Numix-Square/ ]; then
    cp -rH styles/"${style}"/Numix-Square/* "${dir}"/Numix-Square/
    chown -R "$cuser" "${dir}"/Numix-Square/
    gtk-update-icon-cache -f "${dir}"/Numix-Square/
fi

echo "Folder change complete!"
sucess
