#! /usr/bin/python3

from gi.repository import Gtk

message = ("You don't appear to have Numix installed!\n"
           "Please install it and run this script again.")
win = Gtk.Window(type=Gtk.WindowType.TOPLEVEL)
dialog = Gtk.MessageDialog(win, None, Gtk.MessageType.ERROR,
                           Gtk.ButtonsType.OK, message)
dialog.set_deletable(False)
dialog.run()
dialog.destroy()
