#! /usr/bin/python3

# Copyright (C) 2015
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (version 3+) as
# published by the Free Software Foundation. You should have received
# a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.

from gi.repository import Gtk

message = ("You don't appear to have Numix installed!\n"
           "Please install it and run this script again.")
win = Gtk.Window(type=Gtk.WindowType.TOPLEVEL)
dialog = Gtk.MessageDialog(win, None, Gtk.MessageType.ERROR,
                           Gtk.ButtonsType.OK, message)
dialog.set_deletable(False)
dialog.run()
dialog.destroy()
