#!/usr/bin/python3

from gi.repository import Gtk, Gdk
from shutil import copy
import sys, re

def get_default_colour(colour1, colour2, colour3):
    for d in defaults:
        if [colour1, colour2, colour3] == defaults[d]:
            return d
        else:
            continue
    return "custom"

def gdk_to_hex(gdk_colour):
    colours = gdk_colour.to_floats()
    return "#" + "".join(["%02x" % (colour * 255) for colour in colours])

def check_hex(colour):
    match = re.search(r'^#(?:[0-9a-fA-F]{3}){1,2}$', colour)
    if match:
        return True
    else:
        return False

defaults = {"blue": ["#42a5f5", "#1976d2", "#2a74b9"], "brown": ["#8d6e63", "#5d4037", "#634b43"], "green": ["#66bb6a", "#388e3c", "#448647"],
         "grey": ["#bdbdbd", "#757575", "#7f7f7f"], "orange": ["#f57c00", "#e65100", "#ab5d0b"], "pink": ["#f06292", "#ec407a", "#c64077"],
         "purple": ["#7e57c2", "#512da8", "#54398d"], "red": ["#ef5350", "#d32f2f", "#ab3634"], "yellow": ["#ffca28", "#ffb300", "#c79a18"],
         "style 1": ["#c4905e", "#b07f51", "#f9f9f9"], "style 2": ["#e8b07f", "#9e7757", "#9e7757"], "style 3": ["#f2bb64", "#ea9036", "#b58c4b"],
         "style 4": ["#f5c14e", "#e9a439", "#c79d41"], "style 5": ["#ffb300", "#f57c00", "#fff8e1"], "style 6": ["#ffa726", "#ef6c00", "#b17621"]
        }

colours = ["Default", "Blue", "Brown", "Green", "Grey", "Orange", "Pink", "Purple","Red", "Yellow", "Style 1", "Style 2", "Style 3",
            "Style 4", "Style 5", "Style 6", "Custom"]

if len(sys.argv) > 1:
    style=sys.argv[1]
else:
    style="6"

try:
    if int(style) not in range(1,7):
        style = "6"
except:
    style = "6"

if len(sys.argv) > 2:
    colour=sys.argv[2].lower()
else:
    colour = "default"

if colour == "custom":
    colour1 = sys.argv[3] if len(sys.argv) > 3 and check_hex(sys.argv[3]) else "#000000"  
    colour2 = sys.argv[4] if len(sys.argv) > 4 and check_hex(sys.argv[4]) else "#000000"
    colour3 = sys.argv[5] if len(sys.argv) > 5 and check_hex(sys.argv[5]) else "#000000"
elif colour == "default":
    col = defaults["style 6"]
    colour1 = col[0]
    colour2 = col[1]
    colour3 = col[2]
else:
    try:
        col = defaults[colour]
        colour1 = col[0]
        colour2 = col[1]
        colour3 = col[2]
    except:
        colour = "default"
        col = defaults["style 6"]
        colour1 = col[0]
        colour2 = col[1]
        colour3 = col[2]



class NumixFoldersGUI(Gtk.Window):

    def __init__(self, style, colour, colour1, colour2, colour3):
        self.quit = 1
        self.colour1 = colour1
        self.colour2 = colour2
        self.colour3 = colour3
        
        win = Gtk.Window.__init__(self, title="Numix folders GUI")
        self.set_border_width(20)


        #boxes
        vboxmain = Gtk.VBox(spacing=20)
        hboxmain = Gtk.HBox(spacing=0)
        hboxleft = Gtk.HBox()
        vboxpics = Gtk.VBox(homogeneous=True)
        vboxradio = Gtk.VBox(spacing=12, homogeneous=True)
        vboxright = Gtk.VBox(homogeneous=False)
        hboxcombo = Gtk.HBox()
        hboxcolour1 = Gtk.HBox()
        hboxcolour2 = Gtk.HBox()
        hboxcolour3 = Gtk.HBox()
        hboxbuttons = Gtk.HBox()
        self.add(vboxmain)
        
        
        #pixmaps
        self.image1 = Gtk.Image()
        self.image1.set_from_file("./user-home_style1.svg")
        self.image1.show()
        fixed1 = Gtk.Fixed()
        fixed1.put(self.image1, 0, 0)
        vboxpics.pack_start(fixed1, True, True, 0)
        self.image2 = Gtk.Image()
        self.image2.set_from_file("./user-home_style2.svg")
        self.image2.show()
        fixed2 = Gtk.Fixed()
        fixed2.put(self.image2, 0, 0)
        vboxpics.pack_start(fixed2, True, True, 0)
        self.image3 = Gtk.Image()
        self.image3.set_from_file("./user-home_style3.svg")
        self.image3.show()
        fixed3 = Gtk.Fixed()
        fixed3.put(self.image3, 0, 0)
        vboxpics.pack_start(fixed3, True, True, 0)
        self.image4 = Gtk.Image()
        self.image4.set_from_file("./user-home_style4.svg")
        self.image4.show()
        fixed4 = Gtk.Fixed()
        fixed4.put(self.image4, 0, 0)
        vboxpics.pack_start(fixed4, True, True, 0)
        self.image5 = Gtk.Image()
        self.image5.set_from_file("./user-home_style5.svg")
        self.image5.show()
        fixed5 = Gtk.Fixed()
        fixed5.put(self.image5, 0, 0)
        vboxpics.pack_start(fixed5, True, True, 0)
        self.image6 = Gtk.Image()
        self.image6.set_from_file("./user-home_style6.svg")
        self.image6.show()
        fixed6 = Gtk.Fixed()
        fixed6.put(self.image6, 0, 0)
        vboxpics.pack_start(fixed6, True, True,2)
        
        
        #radiobuttons
        self.buttonradio1 = Gtk.RadioButton("Style 1")
        vboxradio.pack_start(self.buttonradio1, False, False, 0)
        self.buttonradio2 = Gtk.RadioButton(group=self.buttonradio1)
        self.buttonradio2.set_label("Style 2")
        vboxradio.pack_start(self.buttonradio2, False, False, 0)
        self.buttonradio3 = Gtk.RadioButton(group=self.buttonradio1)
        self.buttonradio3.set_label("Style 3")
        vboxradio.pack_start(self.buttonradio3, False, False, 0)
        self.buttonradio4 = Gtk.RadioButton(group=self.buttonradio1)
        self.buttonradio4.set_label("Style 4")
        vboxradio.pack_start(self.buttonradio4, False, False, 0)
        self.buttonradio5 = Gtk.RadioButton(group=self.buttonradio1)
        self.buttonradio5.set_label("Style 5")
        vboxradio.pack_start(self.buttonradio5, False, False, 0)
        self.buttonradio6 = Gtk.RadioButton(group=self.buttonradio1)
        self.buttonradio6.set_label("Style 6")
        vboxradio.pack_start(self.buttonradio6, False, False, 2)
        eval('self.buttonradio'+style+'.set_active(True)')
        
        
        #comboboxentry
        colours_store = Gtk.ListStore(str)
        for col in colours:
            colours_store.append([col])
        self.colours_combo = Gtk.ComboBox.new_with_model(colours_store)
        renderer_text = Gtk.CellRendererText()
        self.colours_combo.pack_start(renderer_text, True)
        self.colours_combo.add_attribute(renderer_text, "text", 0)
        if colour and colour in [x.lower() for x in colours]: 
            ind = [x.lower() for x in colours].index(colour)
            self.colours_combo.set_active(ind)
        hboxcombo.pack_start(self.colours_combo, True, True, 30)
        
        
        #colourchooser
        colour11 = Gdk.color_parse(self.colour1)
        colour21 = Gdk.color_parse(self.colour2)
        colour31 = Gdk.color_parse(self.colour3)
        
        self.colourbutton1 = Gtk.ColorButton()
        self.colourbutton1.set_color(colour11)
        self.colourentry1 = Gtk.Entry()
        self.colourentry1.set_text(colour1)
        self.colourentry1.set_max_width_chars(7)
        self.colourentry1.set_max_length(7)
        hboxcolour1.pack_start(self.colourbutton1, False, False, 10)
        hboxcolour1.pack_start(self.colourentry1, False, False, 0)
        
        self.colourbutton2 = Gtk.ColorButton()
        self.colourbutton2.set_color(colour21)
        self.colourentry2 = Gtk.Entry()
        self.colourentry2.set_text(colour2)
        self.colourentry2.set_max_width_chars(7)
        self.colourentry2.set_max_length(7)
        hboxcolour2.pack_start(self.colourbutton2, False, False, 10)
        hboxcolour2.pack_start(self.colourentry2, False, False, 0)
        
        self.colourbutton3 = Gtk.ColorButton()
        self.colourbutton3.set_color(colour31)
        self.colourentry3 = Gtk.Entry()
        self.colourentry3.set_text(colour3)
        self.colourentry3.set_max_width_chars(7)
        self.colourentry3.set_max_length(7)
        hboxcolour3.pack_start(self.colourbutton3, False, False,10)
        hboxcolour3.pack_start(self.colourentry3, False, False, 0)
        
        
        #buttons
        buttonclose = Gtk.Button("_Cancel", use_underline=True)
        buttonok = Gtk.Button("_OK", use_underline=True)
        hboxbuttons.pack_end(buttonok, False, False, 0)
        hboxbuttons.pack_end(buttonclose, False, False, 0)
        
        
        #packing
        vboxmain.pack_start(hboxmain, False, False, 0)
        vboxmain.pack_end(hboxbuttons, True, True, 4)
        
        hboxmain.pack_start(hboxleft, False, False, 0)
        hboxmain.pack_start(vboxright, False, False, 25)
        
        hboxleft.pack_start(vboxpics, True, True, 5)
        hboxleft.pack_end(vboxradio, True, True, 5)
        
        vboxright.pack_start(hboxcombo, False, False, 70)
        vboxright.pack_start(hboxcolour1, False, False, 5)
        vboxright.pack_start(hboxcolour2, False, False, 5)
        vboxright.pack_start(hboxcolour3, False, False, 5)
        
        
        #conect signals
        self.colours_combo.connect("changed", self.update_combo)
        self.colourbutton1.connect("color_set", self.update_entry, 1)
        self.colourentry1.connect("changed", self.update_colourbutton, 1)
        self.colourbutton2.connect("color_set", self.update_entry, 2)
        self.colourentry2.connect("changed", self.update_colourbutton, 2)
        self.colourbutton3.connect("color_set", self.update_entry, 3)
        self.colourentry3.connect("changed", self.update_colourbutton, 3)
        self.buttonradio1.connect("toggled", self.update_style)
        buttonclose.connect("clicked", self.on_close_clicked)
        buttonok.connect("clicked", self.on_ok_clicked)
        self.update_combo(self.colours_combo)
        if colour == "custom":
            self.update_images(self.colour1, self.colour2, self.colour3)
        
    def update_style(self, widget, *arg):
        if widget.get_active():
            self.colourbutton2.set_sensitive(False)
            self.colourbutton3.set_sensitive(False)
            self.colourentry2.set_sensitive(False)
            self.colourentry3.set_sensitive(False)
        else:
            self.colourbutton2.set_sensitive(True)
            self.colourbutton3.set_sensitive(True)
            self.colourentry2.set_sensitive(True)
            self.colourentry3.set_sensitive(True)

    def update_combo(self, widget):
        ind = widget.get_active()
        colour = colours[ind].lower()
        if colour == "custom":
            return
        elif colour == "default":
            (self.colour1, self.colour2, self.colour3) = defaults["style 6"]
            for j in range(1, 7):
                self.update_images_style(str(j), *defaults["style "+str(j)])
        else:
            (self.colour1, self.colour2, self.colour3) = defaults[colour]
            self.update_images(self.colour1, self.colour2, self.colour3)
        self.colourbutton1.handler_block_by_func(self.update_entry)
        self.colourbutton2.handler_block_by_func(self.update_entry)
        self.colourbutton3.handler_block_by_func(self.update_entry)
        self.colourentry1.handler_block_by_func(self.update_colourbutton)
        self.colourentry2.handler_block_by_func(self.update_colourbutton)
        self.colourentry3.handler_block_by_func(self.update_colourbutton)
        self.colourentry1.set_text(self.colour1)
        self.colourentry2.set_text(self.colour2)
        self.colourentry3.set_text(self.colour3)
        self.colourbutton1.set_color(Gdk.color_parse(self.colour1))
        self.colourbutton2.set_color(Gdk.color_parse(self.colour2))
        self.colourbutton3.set_color(Gdk.color_parse(self.colour3))
        self.colourbutton1.handler_unblock_by_func(self.update_entry)
        self.colourbutton2.handler_unblock_by_func(self.update_entry)
        self.colourbutton3.handler_unblock_by_func(self.update_entry)
        self.colourentry1.handler_unblock_by_func(self.update_colourbutton)
        self.colourentry2.handler_unblock_by_func(self.update_colourbutton)
        self.colourentry3.handler_unblock_by_func(self.update_colourbutton)

        
    def update_entry(self, widget, arg):
        colour = widget.get_color()
        if arg==1:
            self.colour1 = gdk_to_hex(colour)
            self.colourentry1.handler_block_by_func(self.update_colourbutton)
            self.colourentry1.set_text(self.colour1)
            self.colourentry1.handler_unblock_by_func(self.update_colourbutton)
        elif arg==2:
            self.colour2 = gdk_to_hex(colour)
            self.colourentry2.handler_block_by_func(self.update_colourbutton)
            self.colourentry2.set_text(self.colour2)
            self.colourentry2.handler_unblock_by_func(self.update_colourbutton)
        elif arg==3:
            self.colour3 = gdk_to_hex(colour)
            self.colourentry3.handler_block_by_func(self.update_colourbutton)
            self.colourentry3.set_text(self.colour3)
            self.colourentry3.handler_unblock_by_func(self.update_colourbutton)
        colour = get_default_colour(self.colour1, self.colour2, self.colour3)
        ind = [x.lower() for x in colours].index(colour)
        self.update_images(self.colour1, self.colour2, self.colour3)
        self.colours_combo.handler_block_by_func(self.update_combo)
        self.colours_combo.set_active(ind)
        self.colours_combo.handler_unblock_by_func(self.update_combo)
        

    def update_colourbutton(self, widget, arg):
        entry = widget.get_text()
        if len(entry) != 7:
            return
        match = re.search(r'^#(?:[0-9a-fA-F]{3}){1,2}$', entry)
        if not match:
            return
        try:
            colour = Gdk.color_parse(entry)
        except:
            return
        if arg==1:
            self.colour1 = entry
            self.colourbutton1.handler_block_by_func(self.update_entry)
            self.colourbutton1.set_color(colour)
            self.colourbutton1.handler_unblock_by_func(self.update_entry)
        elif arg==2:
            self.colour2 = entry
            self.colourbutton2.handler_block_by_func(self.update_entry)
            self.colourbutton2.set_color(colour)
            self.colourbutton2.handler_unblock_by_func(self.update_entry)
        elif arg==3:
            self.colour3 = entry
            self.colourbutton3.handler_block_by_func(self.update_entry)
            self.colourbutton3.set_color(colour)
            self.colourbutton3.handler_unblock_by_func(self.update_entry)
        colour = get_default_colour(self.colour1, self.colour2, self.colour3)
        ind = [x.lower() for x in colours].index(colour)
        self.update_images(self.colour1, self.colour2, self.colour3)
        self.colours_combo.handler_block_by_func(self.update_combo)
        self.colours_combo.set_active(ind)
        self.colours_combo.handler_unblock_by_func(self.update_combo)


    def update_images(self, col1, col2, col3):
        for i in range(1,7):
            filename = "./user-home_style"+str(i)+".svg"
            copy("./styles/"+str(i)+"/Numix/48x48/places/custom-user-home.svg", filename)
            with open(filename, "r") as content_file:
                svg = content_file.read()
            svg = svg.replace("replacecolour1", col1)
            svg = svg.replace("replacecolour2", col2)
            svg = svg.replace("replacecolour3", col3)
            f = open(filename,'w')
            f.write(svg)
            f.close()
        self.image1.set_from_file("./user-home_style1.svg")
        self.image2.set_from_file("./user-home_style2.svg")
        self.image3.set_from_file("./user-home_style3.svg")
        self.image4.set_from_file("./user-home_style4.svg")
        self.image5.set_from_file("./user-home_style5.svg")
        self.image6.set_from_file("./user-home_style6.svg")
    
    
    def update_images_style(self, style, col1, col2, col3):
        filename = "./user-home_style"+str(style)+".svg"
        copy("./styles/"+str(style)+"/Numix/48x48/places/custom-user-home.svg", filename)
        with open(filename, "r") as content_file:
            svg = content_file.read()
        svg = svg.replace("replacecolour1", col1)
        svg = svg.replace("replacecolour2", col2)
        svg = svg.replace("replacecolour3", col3)
        f = open(filename,'w')
        f.write(svg)
        f.close()
        eval('self.image'+str(style)+'.set_from_file("./user-home_style'+str(style)+'.svg")')
        

    def on_close_clicked(self, button):
        self.quit = 1
        Gtk.main_quit()
    
    
    def on_ok_clicked(self, button):
        self.quit = 0
        Gtk.main_quit()


win = NumixFoldersGUI(style, colour, colour1, colour2, colour3)
win.connect("delete-event", Gtk.main_quit)
win.set_resizable(False)
win.show_all()
Gtk.main()

try:
    style = [win.buttonradio1.get_group()[::-1].index(r)+1 for r in win.buttonradio1.get_group() if r.get_active()][0]
    colour = colours[win.colours_combo.get_active()].lower()
except:
    sys.exit("Cancel")
if not win.quit:
    print(style)
    print(colour)
    print(win.colour1)
    print(win.colour2)
    print(win.colour3)
else:
    sys.exit("Cancel")


