#!/usr/bin/python3

from gi.repository import Notify, Gtk, GLib


def dialog_destroy(widget):
    widget.destroy()
    return True

try:
    Notify.init("numix-folders")
    n = Notify.Notification.new("Numix-folders", "applying...", "gtk-info")
    n.show()
except:
    message = "Applying..."
    dialog = Gtk.MessageDialog(None, None,Gtk.MessageType.INFO, Gtk.ButtonsType.NONE, message)
    dialog.set_deletable(True)
    GLib.timeout_add(3000, dialog_destroy, dialog)
    dialog.run()
    dialog.destroy()


